[project]
name = "mcp-local-context"
version = "0.1.2"
description="Local Documentation MCP Server with RAG"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.1",
    "vlite>=0.2.0"
]
